<a href="https://colab.research.google.com/github/xd932/Deep_Learning_2024/blob/main/FeedForward_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim

# Define a custom neural network class for multiplication
class MultiplyNetwork(nn.Module):
    def __init__(self):
        super(MultiplyNetwork, self).__init__()
        self.fc1 = nn.Linear(2, 1)  # Two input features, one output (product)

    def forward(self, x):
        x = self.fc1(x)
        return x

# Create an instance of the multiplication network
model = MultiplyNetwork()

# Define a sample input
input_data = torch.tensor([3.0, 4.0])  # Input two numbers to be multiplied (e.g., 3 and 4)

# Perform a forward pass to compute the product
product = model(input_data)

# Print the product
print(product.item())  # Print the product as a single float



#Since here the training is not done for model, we will get close to answer of multiplication but not exact.
#Intersesrting thing about this is each time you run the code , ouput will move away from answer toward negative.


-3.391423463821411


In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim

# Define a custom neural network class for multiplication
class MultiplyNetwork(nn.Module):
    def __init__(self):
        super(MultiplyNetwork, self).__init__()
        self.fc1 = nn.Linear(2, 1)  # Two input features, one output (product)

    def forward(self, x):
        x = self.fc1(x)
        return x

# Create an instance of the multiplication network
model = MultiplyNetwork()

# Define a sample input
input_data = torch.tensor([3.0, 4.0])  # Input two numbers to be multiplied (e.g., 3 and 4)

# Define the target (ground truth) value
target = torch.tensor([12.0])  # The product of 3 and 4

# Define a loss function (mean squared error) and an optimizer (e.g., SGD)
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)

# Training loop
for epoch in range(1000):
    # Forward pass
    output = model(input_data)

    # Compute the loss
    loss = criterion(output, target)

    # Backpropagation and optimization
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    print(output)

# After certain epochs 12 will be achieved but the loop willl still be running continously so need to use condition to break the loop

# After training, you can check the network's output
product = model(input_data)
print(product.item())  # Should be close to 12.0 if the training is successful


tensor([-0.8464], grad_fn=<ViewBackward0>)
tensor([5.8337], grad_fn=<ViewBackward0>)
tensor([9.0402], grad_fn=<ViewBackward0>)
tensor([10.5793], grad_fn=<ViewBackward0>)
tensor([11.3181], grad_fn=<ViewBackward0>)
tensor([11.6727], grad_fn=<ViewBackward0>)
tensor([11.8429], grad_fn=<ViewBackward0>)
tensor([11.9246], grad_fn=<ViewBackward0>)
tensor([11.9638], grad_fn=<ViewBackward0>)
tensor([11.9826], grad_fn=<ViewBackward0>)
tensor([11.9917], grad_fn=<ViewBackward0>)
tensor([11.9960], grad_fn=<ViewBackward0>)
tensor([11.9981], grad_fn=<ViewBackward0>)
tensor([11.9991], grad_fn=<ViewBackward0>)
tensor([11.9996], grad_fn=<ViewBackward0>)
tensor([11.9998], grad_fn=<ViewBackward0>)
tensor([11.9999], grad_fn=<ViewBackward0>)
tensor([12.0000], grad_fn=<ViewBackward0>)
tensor([12.0000], grad_fn=<ViewBackward0>)
tensor([12.0000], grad_fn=<ViewBackward0>)
tensor([12.0000], grad_fn=<ViewBackward0>)
tensor([12.0000], grad_fn=<ViewBackward0>)
tensor([12.0000], grad_fn=<ViewBackward0>)
tensor([12.00

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim

# Define a custom neural network class for multiplication
class MultiplyNetwork(nn.Module):
    def __init__(self):
        super(MultiplyNetwork, self).__init__()
        self.fc1 = nn.Linear(2, 1)  # Two input features, one output (product)

    def forward(self, x):
        x = self.fc1(x)
        return x

# Create an instance of the multiplication network
model = MultiplyNetwork()

# Define a sample input
input_data = torch.tensor([3.0, 4.0])  # Input two numbers to be multiplied (e.g., 3 and 4)

# Define the target (ground truth) value
target = torch.tensor([12.0])  # The product of 3 and 4

# Define a loss function (mean squared error) and an optimizer (e.g., SGD)
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)

# Training loop
for epoch in range(1000):
    # Forward pass
    output = model(input_data)

    # Compute the loss
    loss = criterion(output, target)

    # Backpropagation and optimization
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    print(output)
    if abs(output.item() - target.item())< 1e-6:
      print(f"Training stopped at epoch {epoch} because output is close to target.")
      break

# After training, you can check the network's output
product = model(input_data)
print(product.item())  # Should be close to 12.0 if the training is successful


tensor([-0.7555], grad_fn=<ViewBackward0>)
tensor([5.8773], grad_fn=<ViewBackward0>)
tensor([9.0611], grad_fn=<ViewBackward0>)
tensor([10.5893], grad_fn=<ViewBackward0>)
tensor([11.3229], grad_fn=<ViewBackward0>)
tensor([11.6750], grad_fn=<ViewBackward0>)
tensor([11.8440], grad_fn=<ViewBackward0>)
tensor([11.9251], grad_fn=<ViewBackward0>)
tensor([11.9641], grad_fn=<ViewBackward0>)
tensor([11.9827], grad_fn=<ViewBackward0>)
tensor([11.9917], grad_fn=<ViewBackward0>)
tensor([11.9960], grad_fn=<ViewBackward0>)
tensor([11.9981], grad_fn=<ViewBackward0>)
tensor([11.9991], grad_fn=<ViewBackward0>)
tensor([11.9996], grad_fn=<ViewBackward0>)
tensor([11.9998], grad_fn=<ViewBackward0>)
tensor([11.9999], grad_fn=<ViewBackward0>)
tensor([12.0000], grad_fn=<ViewBackward0>)
tensor([12.0000], grad_fn=<ViewBackward0>)
tensor([12.0000], grad_fn=<ViewBackward0>)
tensor([12.0000], grad_fn=<ViewBackward0>)
tensor([12.0000], grad_fn=<ViewBackward0>)
tensor([12.0000], grad_fn=<ViewBackward0>)
Training stop